{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if and .Values.controllers.pdb .Values.controllers.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "slurm-bridge.name" . }}-controllers
  namespace: {{ include "slurm-bridge.namespace" . }}
spec:
  maxUnavailable: {{ .Values.controllers.pdb.maxUnavailable }}
  minAvailable: {{ .Values.controllers.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "slurm-bridge.controllers.selectorLabels" . | nindent 6 }}
{{- end }}{{- /* if .Values.controllers.pdb && .Values.controllers.pdb.enabled */}}
