{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "slurm-bridge.controllers.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slurm-bridge.controllers.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "slurm-bridge.controllers.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: health
      protocol: TCP
      port: 8081
      targetPort: 8081
