---
apiVersion: scheduling.x-k8s.io/v1alpha1
kind: PodGroup
metadata:
  name: podgroup-sleep-dra
  namespace: slurm-bridge
  annotations:
    slurmjob.slinky.slurm.net/job-name: podgroup-sleep-dra
spec:
  minMember: 2
---
apiVersion: v1
kind: Pod
metadata:
  name: sleep1-dra
  namespace: slurm-bridge
  labels:
    app: podgroup-sleep-dra
    scheduling.x-k8s.io/pod-group: podgroup-sleep-dra
spec:
  schedulerName: slurm-bridge-scheduler
  restartPolicy: Never
  containers:
    - name: sleep
      image: busybox:stable
      command: [sh, -c, sleep 3]
      resources:
        requests:
          cpu: '1'
          memory: 100Mi
        limits:
          cpu: '1'
          memory: 100Mi
          deviceclass.resource.kubernetes.io/gpu.example.com: 1
---
apiVersion: v1
kind: Pod
metadata:
  name: sleep2-dra
  namespace: slurm-bridge
  labels:
    app: podgroup-sleep-dra
    scheduling.x-k8s.io/pod-group: podgroup-sleep-dra
spec:
  schedulerName: slurm-bridge-scheduler
  restartPolicy: Never
  containers:
    - name: sleep
      image: busybox:stable
      command: [sh, -c, sleep 3]
      resources:
        requests:
          cpu: '1'
          memory: 100Mi
        limits:
          cpu: '1'
          memory: 100Mi
          deviceclass.resource.kubernetes.io/gpu.example.com: 1
