---
apiVersion: scheduling.x-k8s.io/v1alpha1
kind: PodGroup
metadata:
  name: podgroup-sleep
  namespace: slurm-bridge
  annotations:
    slinky.slurm.net/job-name: podgroup-sleep
spec:
  minMember: 2
---
apiVersion: v1
kind: Pod
metadata:
  name: sleep1
  namespace: slurm-bridge
  labels:
    app: podgroup-sleep
    scheduling.x-k8s.io/pod-group: podgroup-sleep
spec:
  restartPolicy: Never
  containers:
    - name: sleep
      image: busybox:stable
      command: [sh, -c, sleep 3]
      resources:
        requests:
          cpu: '1'
          memory: 100Mi
        limits:
          cpu: '1'
          memory: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: sleep2
  namespace: slurm-bridge
  labels:
    app: podgroup-sleep
    scheduling.x-k8s.io/pod-group: podgroup-sleep
spec:
  restartPolicy: Never
  containers:
    - name: sleep
      image: busybox:stable
      command: [sh, -c, sleep 3]
      resources:
        requests:
          cpu: '1'
          memory: 100Mi
        limits:
          cpu: '1'
          memory: 100Mi
