---
apiVersion: v1
kind: Pod
metadata:
  name: pod-pause-cpu
  namespace: slurm-bridge
  annotations:
    slurmjob.slinky.slurm.net/job-name: pod-pause-cpu
spec:
  schedulerName: slurm-bridge-scheduler
  restartPolicy: Never
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.6
      resources:
        requests:
          cpu: '1'
          memory: 100Mi
        limits:
          cpu: '1'
          memory: 100Mi
