---
apiVersion: v1
kind: Pod
metadata:
  name: pod-pause-dra
  namespace: slurm-bridge
  annotations:
    slurmjob.slinky.slurm.net/job-name: pod-pause-dra
spec:
  schedulerName: slurm-bridge-scheduler
  restartPolicy: Never
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.6
      resources:
        requests:
          cpu: '1'
          memory: 100Mi
          deviceclass.resource.kubernetes.io/gpu.example.com: '1'
        limits:
          cpu: '1'
          memory: 100Mi
          deviceclass.resource.kubernetes.io/gpu.example.com: '1'
