---
apiVersion: slinky.slurm.net/v1alpha1
kind: Token
metadata:
  name: slurm-bridge-token
  namespace: slinky
spec:
  jwtHs256KeyRef:
    name: slurm-auth-jwths256
    key: jwt_hs256.key
    namespace: slurm
  secretRef:
    name: slurm-bridge-jwt-token
    key: auth-token
  username: slurm
  refresh: true
  lifetime: 8760h
