{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.admission.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slurm-bridge.admission.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slurm-bridge.admission.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.admission.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "slurm-bridge.admission.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "slurm-bridge.admission.labels" . | nindent 8 }}
    spec:
      {{- with .Values.admission.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "slurm-bridge.admission.name" . }}
      containers:
        - name: {{ include "slurm-bridge.admission.name" . }}
          image: {{ include "slurm-bridge.admission.imageRef" . }}
          imagePullPolicy: IfNotPresent
          env:
            - name: SLURM_JWT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sharedConfig.slurmJwtSecret }}
                  key: auth-token
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
          {{- with .Values.admission.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.admission.nodeSelector }}
          nodeSelector: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.admission.affinity }}
          affinity: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: certificates
              mountPath: /tmp/k8s-webhook-server/serving-certs/
              readOnly: true
            - name: slurm-bridge-config
              mountPath: /etc/slurm-bridge/
              readOnly: true
      {{- with .Values.admission.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: certificates
          secret:
            defaultMode: 420
            secretName: {{ include "slurm-bridge.admission.name" . }}
        - name: slurm-bridge-config
          configMap:
            name: slurm-bridge-config
{{- end }}{{- /* if .Values.admission.enabled */}}
