{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.admission.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "slurm-bridge.admission.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slurm-bridge.admission.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "slurm-bridge.admission.name" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "slurm-bridge.admission.name" . }}
  labels:
    {{- include "slurm-bridge.admission.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "slurm-bridge.admission.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "slurm-bridge.admission.name" . }}
{{- end }}{{- /* if .Values.admission.enabled */}}
