{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.admission.enabled }}
{{- $certNamespacedName := printf "%s/%s" .Release.Namespace (include "slurm-bridge.admission.name" .) -}}
{{- $durationDays := int 3650 -}}
{{- $ca := genCA (include "slurm-bridge.admission.name" .) $durationDays -}}
{{- if not .Values.admission.certManager.enabled }}
{{- $cn := (include "slurm-bridge.admission.name" .) -}}
{{- $dnsList := list (printf "%s.%s" (include "slurm-bridge.admission.name" .) .Release.Namespace) (printf "%s.%s.svc" (include "slurm-bridge.admission.name" .) .Release.Namespace) -}}
{{- $cert := genSignedCert $cn nil $dnsList $durationDays $ca -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slurm-bridge.admission.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slurm-bridge.admission.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end }}{{- /* if not .Values.admission.certManager.enabled */}}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "slurm-bridge.admission.name" . }}
  {{- if .Values.admission.certManager.enabled }}
  annotations:
    certmanager.k8s.io/inject-ca-from: {{ $certNamespacedName | quote }}
    cert-manager.io/inject-ca-from: {{ $certNamespacedName | quote }}
  {{- end }}{{- /* if .Values.admission.certManager.enabled */}}
  labels:
    {{- include "slurm-bridge.admission.labels" . | nindent 4 }}
webhooks:
  - name: pods.slinky.slurm.net
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - {{ .Release.Namespace }}
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        operations: ["CREATE", "UPDATE"]
        scope: Namespaced
    clientConfig:
      {{- if not .Values.admission.certManager.enabled }}
      caBundle: {{ $ca.Cert | b64enc | quote }}
      {{- end }}{{- /* if not .Values.admission.certManager.enabled */}}
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "slurm-bridge.admission.name" . }}
        path: /validate--v1-pod
    admissionReviewVersions: ["v1"]
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "slurm-bridge.admission.name" . }}
  {{- if .Values.admission.certManager.enabled }}
  annotations:
    certmanager.k8s.io/inject-ca-from: {{ $certNamespacedName | quote }}
    cert-manager.io/inject-ca-from: {{ $certNamespacedName | quote }}
  {{- end }}{{- /* if .Values.admission.certManager.enabled */}}
  labels:
    {{- include "slurm-bridge.admission.labels" . | nindent 4 }}
webhooks:
  - name: pods.slinky.slurm.net
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - {{ .Release.Namespace }}
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        operations: ["CREATE", "UPDATE"]
        scope: Namespaced
    clientConfig:
      {{- if not .Values.admission.certManager.enabled }}
      caBundle: {{ $ca.Cert | b64enc | quote }}
      {{- end }}{{- /* if not .Values.admission.certManager.enabled */}}
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "slurm-bridge.admission.name" . }}
        path: /mutate--v1-pod
    admissionReviewVersions: ["v1"]
    sideEffects: None
{{- end }}{{- /* if .Values.admission.enabled */}}
