{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if and .Values.admission.certManager.enabled .Values.admission.enabled }}
---
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing admission serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "slurm-bridge.admission.certManager.selfIssuer" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slurm-bridge.admission.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "slurm-bridge.admission.certManager.rootCA" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slurm-bridge.admission.labels" . | nindent 4 }}
spec:
  commonName: {{ include "slurm-bridge.admission.certManager.rootCA" . }}
  secretName: {{ include "slurm-bridge.admission.certManager.rootCA" . }}
  isCA: true
  duration: {{ .Values.admission.certManager.duration | default "43800h0m0s" | quote }}
  renewBefore: {{ .Values.admission.certManager.renewBefore | default "8760h0m0s" | quote }}
  issuerRef:
    name: {{ include "slurm-bridge.admission.certManager.selfIssuer" . }}
---
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "slurm-bridge.admission.certManager.rootIssuer" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slurm-bridge.admission.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "slurm-bridge.admission.certManager.rootCA" . }}
---
# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "slurm-bridge.admission.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slurm-bridge.admission.labels" . | nindent 4 }}
spec:
  commonName: {{ include "slurm-bridge.admission.certManager.selfCert" . }}
  secretName: {{ include "slurm-bridge.admission.name" . }}
  duration: {{ .Values.admission.certManager.duration | default "43800h0m0s" | quote }}
  renewBefore: {{ .Values.admission.certManager.renewBefore | default "8760h0m0s" | quote }}
  issuerRef:
    name: {{ include "slurm-bridge.admission.certManager.rootIssuer" . }}
  dnsNames:
    - {{ include "slurm-bridge.admission.name" . }}
    - {{ include "slurm-bridge.admission.name" . }}.{{ .Release.Namespace }}.svc
{{- end }}{{- /* if and .Values.admission.certManager.enabled .Values.admission.enabled */}}
