---
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: jobset-dependson
  namespace: slurm-bridge
  annotations:
    slinky.slurm.net/job-name: jobset-dependson
spec:
  replicatedJobs:
    - name: initjob
      replicas: 1
      template:
        spec:
          parallelism: 1
          completions: 1
          template:
            spec:
              containers:
                - name: initjob
                  image: busybox:stable
                  command: [sh, -c, sleep 3]
                  resources:
                    requests:
                      cpu: '1'
                      memory: 100Mi
                    limits:
                      cpu: '1'
                      memory: 100Mi
    - name: workers
      replicas: 2
      dependsOn:
        - name: initjob
          status: Complete
      template:
        spec:
          parallelism: 2
          completions: 2
          backoffLimit: 0
          template:
            spec:
              containers:
                - name: worker1
                  image: busybox:stable
                  command: [sh, -c, sleep 3]
                  resources:
                    requests:
                      cpu: '1'
                      memory: 100Mi
                    limits:
                      cpu: '1'
                      memory: 100Mi
                - name: worker2
                  image: busybox:stable
                  command: [sh, -c, sleep 3]
                  resources:
                    requests:
                      cpu: '1'
                      memory: 100Mi
                    limits:
                      cpu: '1'
                      memory: 100Mi
