---
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: jobset-large
  namespace: slurm-bridge
  annotations:
    slinky.slurm.net/job-name: jobset-large
spec:
  replicatedJobs:
    - name: workers
      replicas: 4
      template:
        spec:
          parallelism: 4
          completions: 4
          backoffLimit: 0
          template:
            spec:
              containers:
                - name: worker1
                  image: busybox:stable
                  command: [sh, -c, sleep 3]
                  resources:
                    requests:
                      cpu: '1'
                      memory: 100Mi
                    limits:
                      cpu: '1'
                      memory: 100Mi
                - name: worker2
                  image: busybox:stable
                  command: [sh, -c, sleep 3]
                  resources:
                    requests:
                      cpu: '1'
                      memory: 100Mi
                    limits:
                      cpu: '1'
                      memory: 100Mi
