---
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: jobset-single
  namespace: slurm-bridge
  annotations:
    slinky.slurm.net/job-name: jobset-single
spec:
  replicatedJobs:
    - name: workers
      replicas: 1
      template:
        spec:
          parallelism: 1
          completions: 1
          backoffLimit: 0
          template:
            spec:
              schedulerName: slurm-bridge-scheduler
              containers:
                - name: worker1
                  image: busybox:stable
                  command: [sh, -c, sleep 3]
                  resources:
                    requests:
                      cpu: '1'
                      memory: 100Mi
                    limits:
                      cpu: '1'
                      memory: 100Mi
