---
apiVersion: v1
kind: Pod
metadata:
  name: pod-single
  namespace: slurm-bridge
  annotations:
    slinky.slurm.net/job-name: pod-single
    slinky.slurm.net/timelimit: '1'
spec:
  schedulerName: slurm-bridge-scheduler
  restartPolicy: Never
  containers:
    - name: pod-single
      image: busybox:stable
      command: [sh, -c, sleep 3]
      resources:
        requests:
          cpu: '1'
          memory: 100Mi
        limits:
          cpu: '1'
          memory: 100Mi
