---
annotations:
  category: HPC
  licenses: Apache-2.0
apiVersion: v2
appVersion: "25.05"
description: Helm Chart for using Slurm as a Kubernetes Scheduler
name: slurm-bridge
type: application
version: 0.3.0
