---
# SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
# SPDX-License-Identifier: Apache-2.0

# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
    - image: slinky.slurm.net/slurm-bridge-scheduler
      context: ../../
      docker:
        dockerfile: Dockerfile
        target: scheduler
    - image: slinky.slurm.net/slurm-bridge-admission
      context: ../../
      docker:
        dockerfile: Dockerfile
        target: admission
    - image: slinky.slurm.net/slurm-bridge-controllers
      context: ../../
      docker:
        dockerfile: Dockerfile
        target: controllers
  tagPolicy:
    inputDigest: {}
  local:
    useDockerCLI: true
deploy:
  helm:
    flags:
      upgrade:
        - --reset-values
    releases:
      - name: slurm-bridge
        chartPath: ./
        valuesFiles:
          - ./values-dev.yaml
        namespace: slurm
        createNamespace: true
