# SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
# SPDX-License-Identifier: Apache-2.0

# -- Overrides the name of the release.
nameOverride: ""

# -- Overrides the full name of the release.
fullnameOverride: ""

# -- Overrides the namespace of the release.
namespaceOverride: ""

# Default values for slurm-bridge.
scheduler:
  # -- The image to use, `${repository}:${tag}`.
  # Ref: https://kubernetes.io/docs/concepts/containers/images/#image-names
  image:
    repository: ghcr.io/slinkyproject/slurm-bridge-scheduler
    tag: ""
  # -- Set the number of replicas to deploy.
  replicaCount: 1
  # -- Enables leader election.
  leaderElect: false
  # -- Set the priority class to use.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass
  priorityClassName: ""
  # -- Set container resource requests and limits for Kubernetes Pod scheduling.
  # Ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits-of-pod-and-container
  resources: {}
    # requests:
    #   cpu: 1
    #   memory: 1Gi
    # limits:
    #   cpu: 2
    #   memory: 4Gi
  # -- (map[string]string) Node label selector for pod assignment.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
  nodeSelector: {}
  # -- Set affinity for Kubernetes Pod scheduling.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}
  # -- Configure pod tolerations.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
  tolerations: []
  # -- (integer) Set the verbosity level of the scheduler.
  verbosity: null

# Configuration settings for the scheduler.
schedulerConfig:
  # -- Set the name of the scheduler.
  schedulerName: slurm-bridge-scheduler
  # -- Set the Slurm MCS Label to use for placeholder jobs.
  # Ref: https://slurm.schedmd.com/sbatch.html#OPT_mcs-label
  mcsLabel: kubernetes
  # -- Set the default Slurm partition to use for placeholder jobs.
  # Ref: https://slurm.schedmd.com/sbatch.html#OPT_partition
  partition: slurm-bridge

# Configuration settings for the admission controller.
admission:
  # -- Enables admission controller.
  enabled: true
  # -- The image to use, `${repository}:${tag}`.
  # Ref: https://kubernetes.io/docs/concepts/containers/images/#image-names
  image:
    repository: ghcr.io/slinkyproject/slurm-bridge-admission
    tag: ""
  # Cert-Manager certificate configurations.
  certManager:
    # -- Enables cert-manager for certificate management.
    enabled: true
    # -- Duration of certificate life.
    duration: 43800h0m0s # 5 year
    # -- Certificate renewal time. Should be before the expiration.
    renewBefore: 8760h0m0s # 1 year
  # -- Set the number of replicas to deploy.
  replicas: 1
  # -- Set the priority class to use.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass
  priorityClassName: ""
  # -- Set container resource requests and limits for Kubernetes Pod scheduling.
  # Ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits-of-pod-and-container
  resources: {}
    # requests:
    #   cpu: 1
    #   memory: 1Gi
    # limits:
    #   cpu: 2
    #   memory: 4Gi
  # -- (map[string]string) Node label selector for pod assignment.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
  nodeSelector: {}
  # -- Set affinity for Kubernetes Pod scheduling.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}
  # -- Configure pod tolerations.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
  tolerations: []
  # -- List of namespaces to be monitored by the pod admission controller.
  # Pods created in any of these namespaces will have their `.spec.schedulerName`
  # changed to slurm-bridge.
  managedNamespaces:
    - slurm-bridge
  # -- A label selector to select namespaces to be monitored by the pod admission controller.
  # If this is set, managedNamespaces will be ignored.
  # Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors
  managedNamespaceSelector: {}

# Configuration settings for the controllers.
controllers:
  # -- The image to use, `${repository}:${tag}`.
  # Ref: https://kubernetes.io/docs/concepts/containers/images/#image-names
  image:
    repository: ghcr.io/slinkyproject/slurm-bridge-controllers
    tag: ""
  # -- Set the number of replicas to deploy.
  replicas: 1
  # -- Set the priority class to use.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass
  priorityClassName: ""
  # -- Set container resource requests and limits for Kubernetes Pod scheduling.
  # Ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits-of-pod-and-container
  resources: {}
    # requests:
    #   cpu: 1
    #   memory: 1Gi
    # limits:
    #   cpu: 2
    #   memory: 4Gi
  # -- (map[string]string) Node label selector for pod assignment.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
  nodeSelector: {}
  # -- Set affinity for Kubernetes Pod scheduling.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}
  # -- Configure pod tolerations.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
  tolerations: []
  # -- (integer) Set the verbosity level of the controllers.
  verbosity: null

# Configurations shared among all components.
sharedConfig:
  # -- The Slurm REST API URL in the form of: `[protocol]://[host]:[port]`
  slurmRestApi: http://slurm-restapi.slurm:6820
  # -- The secret containing a SLURM_JWT token for authentication.
  slurmJwtSecret: slurm-bridge-token
