{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "slurm-bridge.scheduler.name" . }}
  namespace: {{ .Release.Namespace }}
